parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    EmpireDesAmis\User\:
        resource: '../src/'

    EmpireDesAmis\User\DataFixtures\:
        resource: '../fixtures'

    EmpireDesAmis\User\Application\EventListener\OnUserCreated:
        tags: [kernel.event_listener]

    EmpireDesAmis\User\Application\Projection\CreateUserProjection:
        tags: [kernel.event_listener]

    EmpireDesAmis\User\Domain\Service\LogInInterface:
        alias: EmpireDesAmis\User\Infrastructure\EmpireDesAmis\Security\LogIn\LogInEmpireDesAmis

when@dev:
    services:
        EmpireDesAmis\SecurityAuthenticatorBundle\Firebase\Security\Authenticator\AuthenticateUserFromProviderFirebaseInterface:
            alias: EmpireDesAmis\SecurityAuthenticatorBundle\Firebase\Security\Authenticator\AuthenticateUserFromProviderFakeFirebase

when@test:
    services:
        EmpireDesAmis\SecurityAuthenticatorBundle\Firebase\Security\Authenticator\AuthenticateUserFromProviderFirebaseInterface:
            alias: EmpireDesAmis\SecurityAuthenticatorBundle\Firebase\Security\Authenticator\AuthenticateUserFromProviderFakeFirebase

        EmpireDesAmis\SecurityAuthenticatorBundle\Firebase\Security\LogIn\LogInFirebaseInterface:
            alias: EmpireDesAmis\SecurityAuthenticatorBundle\Firebase\Security\LogIn\LogInFakeFirebase