name: Deploy with Kamal

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4'

      - name: Install Kamal CLI via gem
        run: gem install kamal

      - name: Configure Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Deploy with kamal
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          MESSENGER_TRANSPORT_USER_TO_TASTING_DSN: ${{ secrets.MESSENGER_TRANSPORT_USER_TO_TASTING_DSN }}
          MESSENGER_TRANSPORT_USER_DSN: ${{ secrets.MESSENGER_TRANSPORT_USER_DSN }}
          JWT_PASSPHRASE: ${{ secrets.JWT_PASSPHRASE }}
          MAILER_DSN: ${{ secrets.MAILER_DSN }}
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
        run: |
          kamal deploy
